trigger:
  batch: true
  branches:
    include:
    - '*'

variables:
  artifactName: 'enigmatry-entry-blueprint-template'
  dbContextName: 'AppDbContext'
  isRelease: $[startsWith(variables['Build.SourceBranch'], 'refs/heads/releases/')]
  majorMinorVersion: 1.0
  nodeVersion: '18.18.2'
  projectNameAngularApp: enigmatry-entry-blueprint-app
  projectNamePrefix: Enigmatry.Entry.Blueprint

# This determines the build number
name: $(majorMinorVersion)$(Rev:.r)

resources:
  repositories:
    - repository: templates
      type: git
      name: Enigmatry - Azure Pipelines Templates/enigmatry-azure-pipelines-templates

stages:
- stage: 'ci_build'
  displayName: 'Build the web application'
  jobs: 
  - job: build_prerequisites
    displayName: Get the prerequisites for the build
    steps:
    - bash: |
        HASH=$(git rev-parse --short $BUILD_SOURCEVERSION)
        VERSION=$BUILD_BUILDNUMBER-$HASH
      
        echo "Hash: $HASH. Setting build number to: $VERSION"
        echo '##vso[build.updatebuildnumber]'$VERSION
      displayName: 'Set Build number'
 
  - template: build-angular-app-and-dotnet-api.yml@templates
    parameters:
      artifactName: $(artifactName)
      displayName: 'Build Angular App and .net API'
      nodeVersion: $(nodeVersion)
      projectNameAngularApp: $(projectNameAngularApp)
      projectNamePrefix: $(projectNamePrefix)
      runAngularTests: true
      dbContextNames:
      - $(dbContextName)

- stage: 'Deploy_Test'
  pool: 'enigmatry-hosted-windows-agents-test'
  displayName: 'Deploy to the test environment'
  dependsOn: ci_build
  # condition: or(eq(variables['Build.SourceBranch'], 'refs/heads/master'), contains(variables['Build.SourceBranch'], 'BP-XYZ'))
  variables:
  - template: variables/variables.test.yml
  jobs:
  - template: deploy-to-stage.yml
    parameters:
      environment: test
      serviceConnection: 'Enigmatry - Entry Template (Test)'
      