parameters:
- name: environment
- name: serviceConnection
  
jobs:
- template: take-web-app-offline.yml
  parameters:
    jobName: 'take_web_app_offline'
    displayName: 'Take Angular App offline'
    environment: ${{ parameters.environment }}
    subscription: ${{ parameters.serviceConnection }}
    webAppName: $(webAppName)

- template: take-web-app-offline.yml
  parameters:
    jobName: 'take_api_offline'
    displayName: 'Take API offline'
    environment: ${{ parameters.environment }}
    subscription: ${{ parameters.serviceConnection }}
    webAppName: $(webAppName)
    virtualApplication: 'api'

- template: take-web-app-offline.yml
  parameters:
    jobName: 'take_scheduler_offline'
    displayName: 'Take Scheduler offline'
    environment: ${{ parameters.environment }}
    subscription: ${{ parameters.serviceConnection }}
    webAppName: $(schedulerWebAppName)

- template: update-database-job.yml
  parameters:
    dbContextName: $(dbContextName)
    displayName: 'Update the database'
    dependsOn:
    - take_web_app_offline
    - take_api_offline
    - take_scheduler_offline
    environment: ${{ parameters.environment }}
    migrationConnectionString: $(migrationConnectionString)

- template: deploy-web-app.yml
  parameters:
    jobName: 'deploy_scheduler'
    artifactName: $(artifactName)
    displayName: Deploy the Scheduler Web Job
    environment: ${{ parameters.environment }}
    packageName: $(projectNamePrefix).Scheduler
    subscription: ${{ parameters.serviceConnection }}
    webAppName: $(schedulerWebAppName)
    publishProfilePostfix: scheduler
    excludeFilesFromAppDataFlag: false

- template: deploy-web-app.yml
  parameters:
    jobName: 'deploy_angular_app'
    artifactName: $(artifactName)
    displayName: Deploy the Angular web app
    dependsOn:
      - deploy_scheduler #must be after scheduler since they are deployed into same webApp (this is Blueprint specific only)
    environment: ${{ parameters.environment }}
    packageName: $(projectNamePrefix).App
    subscription: ${{ parameters.serviceConnection }}
    webAppName: $(webAppName)
    publishProfilePostfix: app

- template: deploy-web-app.yml
  parameters:
    jobName: 'deploy_api'
    artifactName: $(artifactName)
    displayName: Deploy the BackEnd API
    environment: ${{ parameters.environment }}
    packageName: $(projectNamePrefix).Api
    subscription: ${{ parameters.serviceConnection }}
    webAppName: $(webAppName)
    publishProfilePostfix: api
    virtualApplication: api

- job: git_tag
  displayName: Create Git tag
  dependsOn:
  - deploy_api
  - deploy_scheduler
  steps:
    - checkout: self
      displayName: 'Checkout current repo'
      persistCredentials: true
    - task: CmdLine@2
      displayName: Create Git tag
      inputs:
        script: |
          git tag ${{ parameters.environment }}-$(Build.SourceBranchName)-$(Build.BuildNumber)
          git push origin ${{ parameters.environment }}-$(Build.SourceBranchName)-$(Build.BuildNumber)