parameters:
- name: displayName
- name: projectNameAngularApp

jobs:
- job: 'run_all_angular_tests'
  displayName: ${{ parameters.displayName }}
  timeoutInMinutes: 0
  pool:
    vmImage: 'ubuntu-latest'
  steps:
  - task: Cache@2
    displayName: 'Cache npm Dependencies'
    inputs:
      key: 'npm | "$(Agent.OS)" | $(Build.SourcesDirectory)/${{ parameters.projectNameAngularApp }}/package-lock.json'
      path: '$(Build.SourcesDirectory)/${{ parameters.projectNameAngularApp }}/node_modules'
      cacheHitVar: 'NPM_CACHE_RESTORED'

  - task: Npm@1
    displayName: 'Install node modules'
    inputs:
      command: 'ci'
      workingDir: ${{ parameters.projectNameAngularApp }}
    condition: ne(variables.NPM_CACHE_RESTORED, true)

  - task: Npm@1
    displayName: npm run test
    inputs:
      command: 'custom'
      workingDir: ${{ parameters.projectNameAngularApp }}
      customCommand: 'run test:ci'

  - task: PublishTestResults@2
    displayName: 'Send npm test results to pipelines'
    condition: succeededOrFailed()
    inputs:
      testResultsFiles: '${{ parameters.projectNameAngularApp }}/junit.xml'
