trigger: none

resources:
  repositories:
    - repository: templates
      type: git
      name: Enigmatry - Azure Pipelines Templates/enigmatry-azure-pipelines-templates
      ref: managed-devops-pools

jobs:
- template: run-all-angular-tests.yml@templates
  parameters:
    displayName: 'Run all Angular tests'
    projectNameAngularApp: 'enigmatry-entry-blueprint-app'

- template: run-all-dotnet-tests.yml@templates
  parameters:
    displayName: 'Run all .net tests'
        