parameters:
- name: dbContextName
- name: dependsOn
  type: object
- name: displayName
  default: Update Database
- name: environment
- name: jobName
  default: update_databases
- name: migrationConnectionString

jobs:
- job: ${{ parameters.jobName }}
  ${{ if parameters.dependsOn }}:
    dependsOn: '${{ parameters.dependsOn }}'
  displayName: ${{ parameters.displayName }}
  ${{ if in( parameters['environment'], 'test', 'acceptance') }}:
    pool: 'enigmatry-hosted-windows-agents-${{ parameters.environment }}'
  ${{ if notIn( parameters['environment'], 'test', 'acceptance') }}:
    pool: 'enigmatry-hosted-windows-agents-production'
  steps:
    - task: DownloadPipelineArtifact@2
      displayName: Download migrations artifact
      inputs:
        buildType: 'current'
        artifactName: '$(artifactName)-migrations-$(Build.BuildNumber)'
        targetPath: '$(Pipeline.Workspace)'

    - task: CmdLine@2
      displayName: Execute migrations
      inputs:
        script: $(Pipeline.Workspace)\${{ parameters.dbContextName }}-efbundle.exe --connection "${{ parameters.migrationConnectionString }}"
